In [1]:
import pandas as pd

stock_list = pd.read_csv('jpx_data/stock_list.csv')

In [41]:
sections = stock_list[['SecuritiesCode','Section/Products']]
print(sections.shape)
sec_code_list = sections.loc[sections['Section/Products']!='ETFs/ ETNs']
sec_code_list

(4417, 2)

      SecuritiesCode             Section/Products
0               1301     First Section (Domestic)
19              1332     First Section (Domestic)
20              1333     First Section (Domestic)
26              1352     First Section (Domestic)
37              1375     First Section (Domestic)
...              ...                          ...
4412            9994     First Section (Domestic)
4413            9995     First Section (Domestic)
4414            9996  JASDAQ(Standard / Domestic)
4415            9997     First Section (Domestic)
4416           25935     First Section (Domestic)

[4140 rows x 2 columns]

In [4]:
financials = pd.read_csv('jpx_data/train_files/financials.csv')

C:\Users\torbj\AppData\Local\Temp\ipykernel_12260\3678545494.py:1: DtypeWarning: Columns (14,15,16,17,18,19,42,44) have mixed types. Specify dtype option on import or set low_memory=False.
  financials = pd.read_csv('jpx_data/train_files/financials.csv')

In [42]:
sec_code = 1332.0
data = financials.loc[financials['SecuritiesCode']==sec_code]
data[data.columns[12:]]

,NetSales,OperatingProfit,OrdinaryProfit,Profit,EarningsPerShare,TotalAssets,Equity,EquityToAssetRatio,BookValuePerShare,ResultDividendPerShare1stQuarter,...,ForecastEarningsPerShare,ApplyingOfSpecificAccountingOfTheQuarterlyFinancialStatements,MaterialChangesInSubsidiaries,ChangesBasedOnRevisionsOfAccountingStandard,ChangesOtherThanOnesBasedOnRevisionsOfAccountingStandard,ChangesInAccountingEstimates,RetrospectiveRestatement,NumberOfIssuedAndOutstandingSharesAtTheEndOfFiscalYearIncludingTreasuryStock,NumberOfTreasuryStockAtTheEndOfFiscalYear,AverageNumberOfShares
413,637164000000,19442000000,20696000000,12307000000,44.55,445707000000.0,114030000000.0,0.213,343.6,－,...,43.44,NaN,False,True,False,False,False,277210277.0,942669,276271575.0
414,156341000000,4174000000,3918000000,1654000000,5.99,438602000000.0,108151000000.0,0.204,NaN,－,...,43.44,NaN,False,True,False,False,False,277210277.0,940146,276268883.0
415,303760000000,9812000000,9236000000,4693000000,16.72,440266000000.0,121538000000.0,0.234,NaN,－,...,40.54,NaN,False,True,False,False,False,312430277.0,942538,280662317.0
1590,468821000000,18714000000,20720000000,12377000000,42.54,455006000000.0,132620000000.0,0.249,NaN,－,...,47.29,NaN,False,True,False,False,False,312430277.0,943904,290973976.0
3972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8358,635953000000,22646000000,24884000000,14216000000,48.02,451876000000.0,141205000000.0,0.268,388.38,－,...,64.21,NaN,False,True,False,False,False,312430277.0,945671,296031140.0
11275,162705000000,6720000000,6968000000,5061000000,16.25,464436000000.0,143449000000.0,0.269,NaN,－,...,64.21,NaN,False,False,False,False,False,312430277.0,946522,311484262.0
15631,332826000000,13024000000,13314000000,9247000000,29.69,487176000000.0,149235000000.0,0.267,NaN,－,...,64.21,NaN,False,False,False,False,False,312430277.0,949843,311483077.0
20213,516321000000,20591000000,21336000000,16427000000,52.74,500171000000,158881000000,0.279,NaN,－,...,64.21,NaN,False,False,False,False,False,312430277,952096,311481851
26490,683008000000,23489000000,24840000000,17334000000,55.65,484622000000,157106000000,0.284,442.13,－,...,51.37,NaN,False,False,False,False,False,312430277,948795,311481273
29536,174700000000,7481000000,8219000000,5234000000,16.81,480636000000,159389000000,0.292,NaN,－,...,51.37,NaN,False,False,True,False,False,312430277,949434,311481117
34001,350483000000,10560000000,11952000000.0,6919000000.0,22.22,492820000000.0,164269000000.0,0.294,NaN,－,...,51.42,NaN,False,False,True,False,False,312430277.0,1281652,311405537.0
38304,543261000000,19899000000,22812000000.0,15273000000.0,49.06,504652000000.0,169515000000.0,0.297,NaN,－,...,51.42,NaN,False,False,True,False,False,312430277.0,1283143,311319364.0
44268,712111000000,21685000000,25358000000.0,15379000000.0,49.41,477913000000.0,166158000000.0,0.306,470.28,－,...,56.24,NaN,False,False,True,False,False,312430277.0,1284069,311276763.0
47791,174143000000,5704000000,6067000000.0,3619000000.0,11.63,490967000000.0,168285000000.0,0.303,NaN,－,...,56.24,NaN,False,True,False,False,False,312430277.0,1284900,311145729.0
52052,345402000000,11077000000,12138000000.0,7829000000.0,25.16,490907000000.0,169294000000.0,0.305,NaN,－,...,56.24,NaN,False,True,False,False,False,312430277.0,1286237,311145261.0
56552,526828000000,19068000000,21613000000.0,14791000000.0,47.54,500636000000.0,173924000000.0,0.309,NaN,－,...,56.24,NaN,False,True,False,False,False,312430277.0,1287389,311144642.0
63280,690016000000,22834000000,25807000000.0,14768000000.0,47.47,491533000000.0,172300000000.0,0.312,492.23,－,...,48.21,NaN,False,True,False,False,False,312430277.0,1289063,311143760.0
66035,162254000000,4251000000,4952000000,3189000000,10.25,496893000000.0,172094000000.0,0.308,NaN,－,...,48.21,NaN,False,False,False,False,False,312430277.0,1289372,311141123
71162,320819000000,6968000000,8959000000,5034000000,16.18,481703000000.0,177555000000.0,0.33,NaN,－,...,36.96,NaN,False,False,False,False,False,312430277.0,1290603,311140751
75891,497200000000,15059000000,18796000000,13177000000,42.35,490870000000.0,184035000000.0,0.336,NaN,－,...,36.96,NaN,False,False,False,False,False,312430277.0,1291504,311140270
81641,656491000000,18079000000,22750000000,14452000000,46.45,475415000000.0,187926000000.0,0.357,545.02,－,...,48.21,NaN,False,False,False,False,False,312430277.0,1296387,311139338
85603,165407000000,7049000000,7495000000,5186000000,16.67,496248000000.0,194741000000.0,0.355,NaN,－,...,48.21,NaN,False,True,False,False,False,312430277.0,1297163,311133511.0
90413,339611000000,13866000000,16162000000,11407000000,36.66,506745000000.0,202298000000.0,0.362,NaN,－,...,54.63,NaN,False,True,False,False,False,312430277.0,1191168,311175204.0